#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3.1_AR72614 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Apr 21 22:03:17 CEST 2024
# SW Build 2489853 on Tue Mar 26 04:18:30 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto 82182ea93ec14a33a10b82ad87f2c796 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot sim9_behav xil_defaultlib.sim9 -log elaborate.log
