#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3.1_AR72614 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Apr 21 22:03:17 CEST 2024
# SW Build 2489853 on Tue Mar 26 04:18:30 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim sim9_behav -key {Behavioral:sim_1:Functional:sim9} -tclbatch sim9.tcl -log simulate.log
